### ISSUE TITLE
USB Communication

### ISSUE THREAD

**Issue by KommonO** [oparra22/senior-design#3]
We need to decide once and for all how we are utilizing the USB port. If we are using it for both power and data or just data. Either way, embedded needs to work with Hayden and determine this so we can work on the schematic or code to handle the new setup.

**Comment by hthom** [comment]
Since we can do both, let's do both

**Comment by KommonO** [comment]
This issue has also been solved. We have decided to take advantage of both power and data transmission via the usb cable. The exact device used for USB to USART conversion will be decided by the night of Wednesday March 22 so that the PCB may be ordered on Friday March 24th. Once this has occurred, the information will be uploaded to the github wiki. Shortly, I will share the devices ordered.
